language: android
jdk: oraclejdk8

android:
  components:
    - extra-android-m2repository
    - extra-android-support
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-27

env:
  global:
    - MALLOC_ARENA_MAX=2
    - GRADLE_OPTS="-Xmx4g"
    - ANDROID_SDKS=android-15
    - ANDROID_TARGET=android-15

before_install:
  # Not always needed if Travis' platform-tools are up to date, but keeping for safety
  - echo yes | android update sdk -a --filter platform-tools --no-ui --force

script:
  - ./gradlew assembleDebug assembleRelease
  - ./gradlew testRelease
  - ./gradlew lint || (grep -A20 -B2 'severity="Error"' */build/**/*.xml; exit 1)
  - ./gradlew checkstyle
  - ./gradlew ktlint
  - find . -iname "*XMLRPCClient*java" | xargs grep getSiteId && (echo "You should not use _getSiteId_ in a XMLRPClient, did you mean _selfHostedId_?" && exit 1) || return 0
