version: 2.1

orbs:
  # Using 1.0 of our Orbs means it will use the latest 1.0.x version from https://github.com/wordpress-mobile/circleci-orbs
  android: wordpress-mobile/android@1.0
  slack: circleci/slack@2.5.0

commands:
  copy-gradle-properties:
    steps:
      - run:
          name: Setup gradle.properties
          command: cp example/gradle.properties-example example/gradle.properties
  decrypt-file:
    parameters:
      input:
        type: string
      output:
        type: string
      secret:
        type: string
    steps:
      - run:
          name: Decrypt << parameters.input >>
          command: openssl aes-256-cbc -md sha256 -d -in "<< parameters.input >>" -out "<< parameters.output >>" -k "${<< parameters.secret >>}"
  decrypt-properties-files:
    steps:
      - decrypt-file:
          input: .circleci/gradle.properties.enc
          output: example/gradle.properties
          secret: CIRCLECI_FLUXC_ENCRYPTION_KEY
      - decrypt-file:
          input: .circleci/tests.properties.enc
          output: .circleci/tests.properties
          secret: CIRCLECI_FLUXC_ENCRYPTION_KEY
      - decrypt-file:
          input: .circleci/tests.properties-extra.enc
          output: .circleci/tests.properties-extra
          secret: CIRCLECI_FLUXC_ENCRYPTION_KEY
      - run:
          name: Merge properties files
          command: ./tools/merge_properties.sh .circleci/tests.properties-extra .circleci/tests.properties > example/tests.properties

jobs:
  Lint:
    executor: 
      name: android/default
      api-version: "27"
    steps:
      - checkout
      - android/restore-gradle-cache
      - copy-gradle-properties
      - run:
          name: Check Style
          command: ./gradlew --stacktrace checkstyle ktlint
      - run:
          name: Lint
          command: |
            ./gradlew --stacktrace lintRelease || (grep -A20 -B2 'severity="Error"' */build/**/*.xml; exit 1);
            find . -iname "*XMLRPCClient*java" | xargs grep getSiteId && (echo "You should not use _getSiteId_ in a XMLRPClient, did you mean _selfHostedId_?" && exit 1) || exit 0;
      - android/save-gradle-cache
      - android/save-lint-results
  Unit Tests:
    executor: 
      name: android/default
      api-version: "27"
    steps:
      - checkout
      - android/restore-gradle-cache
      - copy-gradle-properties
      - run:
          name: Unit tests
          command: ./gradlew --stacktrace -PtestsMaxHeapSize=1536m example:testRelease
      - android/save-gradle-cache
      - android/save-test-results
  Firebase Test:
    parameters:
      results-history-name:
        type: string
      package:
        type: string
      timeout:
        type: string
      num-flaky-test-attempts:
        type: integer
      post-slack-status:
        type: boolean
      device:
        type: string
    executor: 
      name: android/default
      api-version: "27"
    steps:
      - checkout
      - android/restore-gradle-cache:
          cache-prefix: connected-tests
      - decrypt-properties-files
      - run:
          name: Build
          command: ./gradlew --stacktrace example:assembleDebug example:assembleDebugAndroidTest
      - decrypt-file:
          input: .circleci/.firebase.secrets.json.enc
          output: .firebase.secrets.json
          secret: FIREBASE_SECRETS_ENCRYPTION_KEY
      - android/firebase-test:
          key-file: .firebase.secrets.json
          results-history-name: << parameters.results-history-name >>
          type: instrumentation
          apk-path: example/build/outputs/apk/debug/example-debug.apk
          test-apk-path: example/build/outputs/apk/androidTest/debug/example-debug-androidTest.apk
          test-targets: package << parameters.package >>
          device: << parameters.device >>
          project: api-project-108380595987
          timeout: << parameters.timeout >>
          num-flaky-test-attempts: << parameters.num-flaky-test-attempts >>
          no-record-video: true
      - android/save-gradle-cache:
          cache-prefix: connected-tests
      - when:
          condition: << parameters.post-slack-status >>
          steps:
            - run:
                name: Setup Slack messages
                when: always
                command: |
                  FIREBASE_URL="https://console.firebase.google.com/project/api-project-108380595987/testlab/histories/bh.fbe4c2866a46a076"
                  echo "export SLACK_FAILURE_MESSAGE=':red_circle: FluxC Connected tests have failed!\nSee $FIREBASE_URL'" >> $BASH_ENV
                  echo "export SLACK_SUCCESS_MESSAGE=':tada: FluxC Connected tests have succeeded!\nSee $FIREBASE_URL'" >> $BASH_ENV
            - slack/status:
                fail_only: 'true'
                failure_message: '${SLACK_FAILURE_MESSAGE}'
                success_message: '${SLACK_SUCCESS_MESSAGE}'
                webhook: '${SLACK_FAILURE_WEBHOOK}'
            - slack/status:
                fail_only: 'false'
                failure_message: '${SLACK_FAILURE_MESSAGE}'
                success_message: '${SLACK_SUCCESS_MESSAGE}'
                webhook: '${SLACK_STATUS_WEBHOOK}'
  WooCommerce API Tests:
    executor: 
      name: android/default
      api-version: "27"
    steps:
      - checkout
      - android/restore-gradle-cache
      - copy-gradle-properties
      - run:
          name: Update Rest Plugin
          command: |
            wget $API_TEST_SITE_URL
            sleep 2m
      - run:
          name: API Tests
          command: |
            cd tests/api 
            gradle test
      - android/save-test-results

workflows:
  fluxc:
    jobs:
      - Lint
      - Unit Tests
      - Firebase Test:
          name: Mocked Connected Tests
          results-history-name: CircleCI FluxC Mocked Tests
          package: org.wordpress.android.fluxc.mocked
          device: model=Nexus5X,version=26,locale=en,orientation=portrait
          timeout: 10m
          num-flaky-test-attempts: 0
          post-slack-status: false
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - develop
    jobs:
      - Firebase Test:
          name: Connected Tests
          results-history-name: CircleCI FluxC Tests
          package: org.wordpress.android.fluxc
          device: model=Nexus5X,version=26,locale=en,orientation=portrait
          timeout: 30m
          num-flaky-test-attempts: 1
          post-slack-status: true
  nightly-api-tests:
    #triggers:
    #  - schedule:
    #      cron: "0 2 * * *"
    #      filters:
    #        branches:
    #          only:
    #            - develop
    jobs:
      - WooCommerce API Tests
